apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - traefik-helmchart.yaml
  - config/middleware-redirect-https.yaml
  - config/dashboard-ingressroute.yaml
  - config/argocd-ingress.yaml
