apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-traefik
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-https@kubernetescrd
    argocd.argoproj.io/sync-wave: "4"
spec:
  ingressClassName: traefik
  rules:
  - host: argocd.starnix.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
  tls:
  - hosts:
    - argocd.starnix.net
    secretName: argocd-server-tls
